dist: trusty
language: rust
rust: nightly
services: docker
sudo: required

matrix:
  exclude:
    # first, clear the matrix
    - rust: nightly
  # then add the targets one by one
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi

script:
  - cargo generate-lockfile
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - sh ci/run-docker.sh $TARGET

